[project]
name = "fastapi-deepseek-tokenizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deepseek-tokenizer>=0.1.3",
    "fastapi[standard]>=0.115.12",
]
